---
title: "Project 1 merged data cleanup"
author: "Matt Chinchilla"
date: "2/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```


```{r}
BitcoinDataMergeV1 <- read_csv("BitcoinDataMergeV1.csv")
```

```{r}
colSums(is.na(BitcoinDataMergeV1))
```

```{r}
str(BitcoinDataMergeV1)
```

```{r, remove columns with multiple NA's}
drops <- c("Transactions last 24h","Transactions avg. per hour","Bitcoins sent last 24h","Bitcoins sent avg. per hour")
BitcoinDataMergeV2 <-  BitcoinDataMergeV1[ , !(names(BitcoinDataMergeV1) %in% drops)]
head(BitcoinDataMergeV2)
```

```{r}
colSums(is.na(BitcoinDataMergeV2))
```

```{r}
BitcoinDataMergeV2 <- na.omit(BitcoinDataMergeV2)
```

```{r}
#Convert Volumne column to real numbers
BitcoinDataMergeV2$Vol. <- gsub('K', 'e3', BitcoinDataMergeV2$Vol.)
BitcoinDataMergeV2$Vol. <- gsub('M', 'e6', BitcoinDataMergeV2$Vol.)
BitcoinDataMergeV2$Vol. <- format(as.numeric(BitcoinDataMergeV2$Vol.), scientific = FALSE) 
                        
#Trim spacing around values
BitcoinDataMergeV2$Vol. <- trimws(BitcoinDataMergeV2$Vol.)

#Convert to numbers
BitcoinDataMergeV2$Vol. <- as.numeric(BitcoinDataMergeV2$Vol.)
```


```{r}
BitcoinDataMergeV2$`Change %` <- gsub("[,$%]","", BitcoinDataMergeV2$`Change %`)

BitcoinDataMergeV2$`Change %` <- as.numeric(BitcoinDataMergeV2$`Change %`)
```

```{r}
View(BitcoinDataMergeV2)
```

```{r}
write.csv(BitcoinDataMergeV2, file = "BitcoinDataMergeV2.csv")
```