---
title: "Project 1 Applied Stats"
author: "Matt Chinchilla"
date: "2/7/2020"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, library}
library(tidyverse)
library(knitr)
library(kableExtra)
library(lubridate)
library(stringr)
library(tseries)
library(forecast)
library(car)
library(plotly)
```

```{r, Set Working Directory}
#wd <- ('/Users/matthewchinchilla/Desktop/SMU/Applied Stats/ProjectDetails/AppliedStats')
#setwd(wd)
```

```{r, Import Bitcoin Data}
myFile <- ('Bitcoin Historical Data - Investing.com.csv')
Bitcoin_data <- read.csv(myFile)
head(Bitcoin_data) %>% kable() %>% kable_styling(bootstrap_options = "striped")
```

#Raw Data Observations
*Vol. Column has trailing "K" 
*Change column has trailing % 

```{r,explore Bitcoin Raw data}
str(Bitcoin_data)#All data is class factor
```

```{r, Date Column Clean}

#Update Column names
Bitcoin_data <- Bitcoin_data %>% 
  rename(
    Change_Percent = Change..
    )

#Update Date column to date format and class
Bitcoin_data$Date <- mdy(Bitcoin_data$Date)

#Update price to number class
Bitcoin_data$Price <- as.numeric(Bitcoin_data$Price)

#Update Open to number class
Bitcoin_data$Open <-  as.numeric(Bitcoin_data$Open)

#Update High to number class
Bitcoin_data$High <- as.numeric(Bitcoin_data$High)

#update Low to number class
Bitcoin_data$Low <- as.numeric(Bitcoin_data$Low)

#Convert Volumne column to real numbers
Bitcoin_data$Vol. <- gsub('K', 'e3', Bitcoin_data$Vol.)
Bitcoin_data$Vol. <- gsub('M', 'e6', Bitcoin_data$Vol.)
Bitcoin_data$Vol. <- format(as.numeric(Bitcoin_data$Vol.), scientific = FALSE) 
                        
#Trim spacing around values
Bitcoin_data$Vol. <- trimws(Bitcoin_data$Vol.)

#Convert to numbers
Bitcoin_data$Vol. <- as.numeric(Bitcoin_data$Vol.)
```

```{r, clean bitcoin data count and view na values in data}

#look for na values 
colSums(is.na(Bitcoin_data))

na <- subset(Bitcoin_data, is.na(Bitcoin_data$Vol.))
na
```

```{r, remove na rows}
Bitcoin_data <- na.omit(Bitcoin_data)

#confirm na rows have been deleted
na <- subset(Bitcoin_data, is.na(Bitcoin_data$Vol.))
na
```

```{r, export clean bitcoin market data}
#write.csv(Bitcoin_data, "/Users/matt/Desktop/SMU/Applied Stats/ProjectDetails/AppliedStats/Bitcoin_MarketData_Clean.csv", row.names = FALSE) 
```

##Exploratory Data Ananlysis on MarketData
```{r, read in clean market data}
Bitcoin_md <- read.csv('/Users/matthewchinchilla/Desktop/SMU/Applied Stats/ProjectDetails/AppliedStats/Bitcoin_MarketData_Clean.csv', header = TRUE)

#Order data in ascending Date order
Bitcoin_md <- Bitcoin_md[order(Date),] 

Bitcoin_md$Date <- as.Date(Bitcoin_md$Date)
```

```{r, plot}
p <- ggplot(Bitcoin_md, aes(x=Date, y=Price)) +
  geom_line() + 
  xlab("Date") + ylab("Bitcoin Price") + ggtitle("Bitcoin Price Over Time")
p
```



```{r}
attach(Bitcoin_md)
acf(Price)
```



```{r}
pacf(Price)
```

```{r}
durbinWatsonTest(lm(Price~1), max.lag = 10)
```

```{r}
bitcoin_ts
```